import * as React from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import { Box, useMediaQuery, Button, Stack, Grid, Alert, Dialog, DialogTitle, DialogContent, DialogContentText, DialogActions } from '@mui/material';
import Typography from '@mui/material/Typography';
import { theme } from 'integrador/styles/material-theme';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import PageHomeLayout from 'integrador/components/layouts/layout-home.component';
import IconButton from '@mui/material/IconButton';
import { useRouter } from "next/router";
import CreditCardOutlinedIcon from '@mui/icons-material/CreditCardOutlined';
import AccountCircleOutlinedIcon from '@mui/icons-material/AccountCircleOutlined';
import useChargeMoney from 'integrador/components/contexts/useChargeMoney';
import ChevronRightIcon from '@mui/icons-material/ChevronRight';

export const CargarDinero: NextPage = () => {

    const laptopOrDesktop = useMediaQuery(theme.breakpoints.up("laptop"));
    const desktop = useMediaQuery(theme.breakpoints.up("desktop"));
    const mobile = useMediaQuery(theme.breakpoints.down("tablet"));
    
    let laptop;
    if (laptopOrDesktop && !desktop)
    laptop = true;
    
    const router = useRouter();
    const {state: chargeMoneyState, dispatch: chargeMoneyDispatch} = useChargeMoney();

    React.useEffect(() => {
        chargeMoneyDispatch({type: "SET_ACCOUNT", payload: ""});
        chargeMoneyDispatch({type: "SET_AMOUNT", payload: 0});
    }, [])


   
    return (
        <>
            <Head>
                <title>Cargar dinero</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Stack sx={{
                    width: '100%', 
                    alignItems: 'center', 
                    justifyContent: 'start'
                }} 
                mt={laptopOrDesktop ? '1rem': mobile ? '0' :'3rem'} 
                spacing={laptop ? 1.3 : 2.5 }
            >


                { mobile && 
                    <Box sx={{display: 'flex', alignItems: 'center', width: '90%', marginTop: '15px'}}>
                        <ChevronRightIcon fontSize='small'sx={{color: 'grey'}}/>
                        <Typography variant='body1'>Cargar dinero</Typography>
                    </Box>
                }

                <Box sx={{
                    backgroundColor: 'primary.main', 
                    width: '90%', 
                    borderRadius: '10px',
                    padding:'1.5rem 1rem',
                    display: 'flex',
                    justifyContent: 'space-between',
                    cursor: 'pointer'
                    }}
                    onClick={() => {router.push('cargarDinero/cuenta')}} 
                >
                    <Box sx={{display: 'flex', justifyContent: 'space-between', alignItems: 'center'}}>
                        <IconButton>
                            <AccountCircleOutlinedIcon color='secondary'/>
                        </IconButton>
                        <Typography color='secondary' variant={'body1'}>Transferencia bancaria</Typography>
                    </Box>
                    <IconButton>
                        <ArrowForwardIcon color='secondary'/>
                    </IconButton>
                </Box>

                <Box sx={{
                    backgroundColor: 'primary.main', 
                    width: '90%', 
                    borderRadius: '10px',
                    padding:'1.5rem 1rem',                    
                    display: 'flex',
                    justifyContent: 'space-between',
                    cursor: 'pointer'
                    }}
                    onClick={() => {router.push('/cargarDinero/tarjeta')}} >
                        <Box sx={{display: 'flex', justifyContent: 'space-between', alignItems: 'center'}}>
                            <IconButton>
                                <CreditCardOutlinedIcon color='secondary'/>
                            </IconButton>
                            <Typography color='secondary' variant={'body1'}>Seleccionar tarjeta</Typography>
                        </Box>
                        <IconButton>
                            <ArrowForwardIcon color='secondary'/>
                        </IconButton>
                    </Box>
            </Stack>
        </>
        
    )
}

(CargarDinero as any).Layout = PageHomeLayout;

export default CargarDinero;
