import type {NextPage} from 'next'
import Head from 'next/head'
import BodySingle from "integrador/components/layouts/body/single/body-single.component";
import Container from '@mui/material/Container';
import LogIn from 'integrador/components/forms/logIn/log-in-form.component';
import { LoginProvider } from 'integrador/components/contexts/LoginContext';
import { StepProvider } from 'integrador/components/contexts/StepContext';
import { useMediaQuery } from '@mui/material';
import { theme } from 'integrador/styles/material-theme';
import { useEffect } from 'react';
import { useRouter } from 'next/router';


export const LogInPage: NextPage = () => {

    const laptopOrDesktop = useMediaQuery(theme.breakpoints.up("laptop"));

    const router = useRouter();

    useEffect(()=>{
        const tokenId = localStorage.getItem("token");
        if (tokenId ) {
          router.push("/home");
        }
    }, [])

    return (
        <>
            <Head>
                <title>Iniciar sesion</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <BodySingle>

                <Container sx={{
                    display: 'flex', 
                    flexWrap: 'wrap', 
                    justifyContent: 'center',
                    height: '100%', 
                    alignContent: laptopOrDesktop ? 'center' : "start", 
                    }} maxWidth={false}>
                    <LoginProvider>
                        <StepProvider>
                            <LogIn/>
                        </StepProvider>
                    </LoginProvider>

                </Container>

            </BodySingle>
        </>
    )
}

// (LogInPage as any).Layout = SignInLayout;


export default LogInPage;
