import type {NextPage} from 'next'
import Head from 'next/head'
import BodySingle from "integrador/components/layouts/body/single/body-single.component";
import Container from '@mui/material/Container';
import SignInLayout from 'integrador/components/layouts/layout-sign-in.component';
import SignInForm from 'integrador/components/forms/signIn/sign-in-form.component';
import { useEffect } from 'react';
import { useRouter } from 'next/router';


export const SignIn: NextPage = () => {

    const router = useRouter();

    useEffect(()=>{
        const tokenId = localStorage.getItem("token");
        if (tokenId ) {
          router.push("/home");
        }
      }, [])

    return (
        <>
            <Head>
                <title>Crear cuenta</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <BodySingle>

                <Container sx={{display: 'flex', flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center'}} maxWidth={false}>
                    <SignInForm/>
                </Container>

            </BodySingle>
        </>
    )
}

(SignIn as any).Layout = SignInLayout;


export default SignIn;
