import { Box, CircularProgress, Stack, Typography, useMediaQuery } from "@mui/material";
import PageHomeLayout from "integrador/components/layouts/layout-home.component";
import type { NextPage } from "next";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { GET_ACTIVITY } from "integrador/pages/api/api";
import ActivitySummary, { Transaction } from "integrador/components/activitySummary/ActivitySummary";
import { theme } from "integrador/styles/material-theme";
import Head from "next/head";
import Services from "integrador/components/services/Services";
import { services } from "services";

export const ActivityPage = () => {
    const router = useRouter();
    const [transactions, setTransactions] = useState<Transaction[]>();

    const mobile = useMediaQuery(theme.breakpoints.down("tablet"));
    const laptopOrDesktop = useMediaQuery(theme.breakpoints.up("laptop"));
    const desktop = useMediaQuery(theme.breakpoints.up("desktop"));

    let laptop;
    if (laptopOrDesktop && !desktop)
        laptop = true;


    useEffect(() => {
        const token = localStorage.getItem("token");
        if(!token) {
        router.push('/');
        }
    }, [])


    return (
        <>
        <Head>
                <title>Pagar servicios</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
        </Head>

        <Stack sx={{ width: '100%', alignItems: 'center', justifyContent: 'start' }} 
            mt={laptopOrDesktop ? '1rem': mobile ? '0' :'3rem'} 
            spacing={laptop ? 1.3 : 2.5 }
            zIndex={3}
        >
            <Services services={services}/>
        </Stack>
        </>
    )
};

(ActivityPage as any).Layout = PageHomeLayout;

export default ActivityPage;